apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: my-deployment 
spec: 
  replicas: {{ .Values.deployment.replicas}}
  selector: 
    matchLabels:
      app: nginx
      project: expense 
  template: 
    metadata:
      labels: 
        app: nginx
        project: expense
    spec: 
      containers:
      - name: nginx 
        image: shaikmustafa/netflix
        ports:
        - containerPort: 80