apiVersion: v1 
kind: Service 
metadata: 
  name: frontend
spec: 
  type: LoadBalancer
  selector: 
    project: expense 
    demo: deplyoment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: {{ .Values.service.nodePort}}